import { ScrollSmoother } from "@/components/gsap/scroll-smoother";
import { Noise } from "@/components/noise";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Unbounded } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const unbounded = Unbounded({
  variable: "--font-unbounded",
  weight: ["400", "900"],
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ScrollSmoother>
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${unbounded.variable} antialiased`}
        >
          <div className="w-screen h-screen" id="smooth-wrapper">
            <div id="smooth-content">
              {children}
            </div>
          </div>
          <Noise />
        </body>
      </ScrollSmoother>
    </html>
  );
}
